exp: 
  dir: Exps/
  name: fullband

# seed: 614020

datas:
  _target_: look2hear.datas.MovingDataModuleRemix
  train_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/train
  val_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/val-enh-noise
  test_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/test
  num_spks: 1
  sample_rate: 16000
  num_samples: 50000
  duration: 4.0
  batch_size: 9
  num_workers: 8
  is_mono: true
  noise_type: noise

model:
  _target_: look2hear.models.fullband.Fullband
  num_freqs: 257
  hidden_size: 512
  sequence_model: LSTM
  output_activate_function: false
  look_ahead: 2
  n_fft: 512
  hop_length: 256
  win_length: 512
  norm_type: offline_laplace_norm
  weight_init: True
  sample_rate: 16000

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  patience: 5
  factor: 0.5

loss:
  _target_: look2hear.losses.FullbandLoss
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  win_length: ${model.win_length}
  
metrics:
  _target_: look2hear.losses.FullbandEval
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  win_length: ${model.win_length}
  

system:
  _target_: look2hear.system.audio_litmodule.AudioLightningModule

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  patience: 10
  mode: min
  verbose: true

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${exp.dir}/${exp.name}/checkpoints
  monitor: val_loss
  mode: min
  verbose: true
  save_top_k: 5
  save_last: true
  filename: '{epoch}-{val_loss:.4f}'

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${exp.name}
  save_dir: ${exp.dir}/${exp.name}/logs
  offline: false
  project: MovingData-Enhencement

trainer:
  _target_: pytorch_lightning.Trainer
  devices: [0]
  max_epochs: 500
  sync_batchnorm: true
  gradient_clip_val: 10.0
  default_root_dir: ${exp.dir}/${exp.name}/
  accelerator: cuda
  limit_train_batches: 1.0
  fast_dev_run: false