exp: 
  dir: Exps/
  name: taylorsenet

# seed: 614020

datas:
  _target_: look2hear.datas.MovingDataModuleRemix
  train_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/train
  val_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/val-enh-noise
  test_dir: ../SonicSim-SonicSet/SonicSet/scene_datasets/mp3d/test
  num_spks: 1
  sample_rate: 16000
  num_samples: 50000
  duration: 4.0
  batch_size: 9
  num_workers: 8
  is_mono: true
  noise_type: noise

model:
  _target_: look2hear.models.taylorsenet.TaylorSENet
  cin: 2
  k1: [1, 3]
  k2: [2, 3]
  c: 64
  kd1: 5
  cd1: 64
  d_feat: 256
  dilations: [1, 2, 5, 9]
  p: 2
  fft_num: 320
  order_num: 3
  n_fft: 320
  hop_length: 160
  win_length: 320
  intra_connect: cat
  inter_connect: cat
  norm_type: IN
  is_causal: true
  is_u2: true
  is_param_share: false
  is_encoder_share: false
  sample_rate: 16000

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0002
  weight_decay: 0.

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  patience: 5
  factor: 0.5

loss:
  _target_: look2hear.losses.TaylorSENetLoss
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  win_length: ${model.win_length}
  
metrics:
  _target_: look2hear.losses.TaylorSENetEval
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  win_length: ${model.win_length}
  

system:
  _target_: look2hear.system.audio_litmodule.AudioLightningModule

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  patience: 10
  mode: min
  verbose: true

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${exp.dir}/${exp.name}/checkpoints
  monitor: val_loss
  mode: min
  verbose: true
  save_top_k: 5
  save_last: true
  filename: '{epoch}-{val_loss:.4f}'

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${exp.name}
  save_dir: ${exp.dir}/${exp.name}/logs
  offline: false
  project: MovingData-Enhencement

trainer:
  _target_: pytorch_lightning.Trainer
  devices: [0]
  max_epochs: 500
  sync_batchnorm: true
  gradient_clip_val: 5.0
  default_root_dir: ${exp.dir}/${exp.name}/
  accelerator: cuda
  limit_train_batches: 1.0
  fast_dev_run: false